ntaps/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
import ntaps_profile.urls as ntaps_profile
import ntaps_add_friend.urls as ntaps_add_friend
import ntaps_update_status.urls as ntaps_update_status
import ntaps_stats.urls as ntaps_stats

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(ntaps_profile,namespace='profile')),
    url(r'^add_friend/', include(ntaps_add_friend,namespace='add_friend')),
    url(r'^update_status/', include(ntaps_update_status,namespace='update_status')),
    url(r'^stats/', include(ntaps_stats,namespace='stats')),
    url(r'^$', RedirectView.as_view(permanent=True, url='/update_status/'))
]

ntaps_update_status/urls.py
from .views import index, add_status, add_comment, delete_status
from django.conf.urls import url

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_status', add_status, name='add_status'),
	#url(r'^add_comment', add_comment, name='add_comment'),
	#url(r'^add_comment/(?P<pk>\d+)/comment/$', add_comment, name='add_comment'),
	url(r'^add_comment/(?P<pk>[0-9]+)/$', add_comment, name='add_comment'),
	url(r'^delete_status/(?P<object_id>[0-9]+)',delete_status,name='delete_status'),
	#url(r'^delete_status', delete_status, name='delete_status'),
]

ntaps_update_status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	status = models.TextField(max_length=160)
	created_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.status

class Comment(models.Model):
	comment = models.TextField(max_length=160)
	created_date = models.DateTimeField(auto_now_add=True)
	status = models.ForeignKey(Status, null=True, blank=True)

	def __str__(self):
		return self.comment

ntaps_update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi status',
    }
    description_attrs ={
    	'type':'text',
    	'rows':4,
    	'class':'status-form-textarea',
    	'placeholder':"What's on your mind?"
    }

    #name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    #email = forms.EmailField(required=False, widget=forms.EmailInput(attrs=attrs))
    status = forms.CharField(widget=forms.Textarea(attrs=description_attrs), required=True, label='')


class Comment_Form(forms.Form):
    error_messages ={
        'required':'Tolong isi comment'
    }
    description_attrs ={
        'type':'text',
        'rows':1,
        'class':'comment-form-textarea',
        'placeholder':'Please give a comment'
    }
    comment = forms.CharField(widget=forms.Textarea(attrs=description_attrs), required=True, label='')

ntaps_update_status/views.py
from django.http import HttpResponseRedirect
from .forms import Status_Form, Comment_Form
from .models import Status, Comment
from django.shortcuts import render, redirect, get_object_or_404
from ntaps_profile.models import Profile

# Create your views here.

status_dict ={}

response = {'author': "Ling In"} #TODO Implement yourname
def index(request):
    html = 'update_status/update_status.html'
    #TODO Implement, isilah dengan 6 kata yang mendeskripsikan anda
    response['status_form'] = Status_Form
    response['comment_form'] = Comment_Form
    response['profile'] = Profile
    status = Status.objects.all().order_by('-created_date')
    response['status'] = status
    return render(request, html, response)

def add_status(request):
	form = Status_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['status'] = request.POST['status']
		status = Status(status=response['status'])
		status.save()
		return redirect('/update_status/')
	else:
		return HttpResponseRedirect('/update_status/')

def add_comment(request, pk):
	status = Status.objects.get(pk=pk)
	form = Comment_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['comment'] = request.POST['comment']
		comment=Comment(comment=response['comment'])
		comment.status = status
		comment.save()
		return redirect('/update_status/')
	else:
		return HttpResponseRedirect('/update_status/')

def delete_status(request, object_id):
	status = Status.objects.get(pk=object_id)
	status.delete()
	return HttpResponseRedirect('/update_status/')

ntaps_update_status/templates/update_status/update_status.html
{% extends "update_status/layout/base.html" %}

{% block content %}
<div class="wrapper-page">
    <div class="wrapper-kiri">
        <div class="wrapper-content">
        <h1 class="friend-title text-white">Update Status</h1>
        <form id="form" method="POST" action="{% url 'update_status:add_status' %}" class="form-main">
            {% csrf_token %}
            {{ status_form }}
            <br>
            <button type="submit" class="btn btn-default" style="float: right;">Post Status</button>
            <br>
        </form>
        </div>
    </div>
    <div class="wrapper-kanan">
        <div class="wrapper-content">
        <h1 class="recent-updates text-white"> Recent Updates</h1>
        <hr class="divider">
        <div class="scrollable">
        <div class="flex-list">
            {% for i in status %}
            <div class="flex-list-item friend-list-item">
                <!-- <img class="img-circle" src="https://vignette.wikia.nocookie.net/spongebob/images/9/95/Hash.jpg/revision/latest?cb=20120624212303" alt = "Me" style="width: 50px; height: 50px;"> -->
                <div class="flex-list-item-post">
                    <h3>{{profile.name}}</h3>
                    <h4>{{i.status}}</h4>
                    <h5>{{i.created_date}}</h5>
                </div>
                <div class="flex-list-item-comment">
                    <div class="flex-list-item-comment-button" data-id="{{data.id}}">Comment</div>
                </div>
                <div class="flex-list-item-delete">
                    <div class="flex-list-item-delete-button" data-id="{{i.id}}"><a href="{% url 'update_status:delete_status' object_id=i.id%}" style="color: white">Delete</a></div>
                </div>
            </div>
                <div class="flex-list-item-comment-section">
                    <div class="comment-section">
                        <div class="comment-section-comment">
                            <h3>Comment</h3>
                            {% if i.comment_set.all %}
                                {% for comment in i.comment_set.all %}
                                    <h4>{{profile.name}}</h4>
                                    <h5>{{comment.comment}}</h5>
                                    <h6>{{comment.created_date}}</h6>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="comment-section-form">
                        <form id="form" method="POST" action="{% url 'update_status:add_comment' pk=i.id%}" class="form-comment" style="color: black">
                            {% csrf_token %}
                            {{ comment_form }}
                            <input id="submit" type="submit" class="btn" value="Submit" style="bottom: -10px">
                            <br>
                        </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        </div>
    </div>
    </div>
</div>
{% endblock %}