ntaps/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
import ntaps_profile.urls as ntaps_profile
import ntaps_add_friend.urls as ntaps_add_friend
import ntaps_update_status.urls as ntaps_update_status
import ntaps_stats.urls as ntaps_stats

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(ntaps_profile,namespace='profile')),
    url(r'^add_friend/', include(ntaps_add_friend,namespace='add_friend')),
    url(r'^update_status/', include(ntaps_update_status,namespace='update_status')),
    url(r'^stats/', include(ntaps_stats,namespace='stats')),
    url(r'^$', RedirectView.as_view(permanent=True, url='/update_status/'))
]

ntaps_stats/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

ntaps_stats/models.py
from django.db import models

# Create your models here.

ntaps_stats/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from ntaps_add_friend.models import Friend
from ntaps_update_status.models import Status
from ntaps_profile.views import name

response = {}
def index(request):
    response['friend_total'] = Friend.objects.count()
    response['status_total'] = Status.objects.count()
    response['latest_status'] = Status.objects.last()
    response['name'] = name
    html = 'stats/ntaps_stats.html'
    return render(request, html, response)

# Create your views here.

ntaps_stats/templates/stats/partials/footer.html
<div class="footer">
  <p>&copy; 2017 ntaps sabeb</p>
</div>

ntaps_stats/templates/stats/partials/header.html
<link href="https://fonts.googleapis.com/css?family=Orbitron:900" rel="stylesheet">
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'update_status:index' %}#update_status"><img class="homelogo" src="http://pngimages.net/sites/default/files/linkedin-logo-png-image-75824.png">NTAPS SABEB</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'update_status:index' %}#update_status"><img class="navbarstatus" src="https://cdn1.iconfinder.com/data/icons/your-needs-vol-5/16/sms_chat_Message_information_memo_whatsapp_1-128.png"></a></li>
        <li><a href="{% url 'profile:index' %}#profile"><img class="navbarprofile" src="https://image.flaticon.com/icons/png/512/64/64572.png"></a> </li>
        <li><a href="{% url 'add_friend:index' %}#add_friend"><img class="navbaraddf" src="https://d30y9cdsu7xlg0.cloudfront.net/png/138580-200.png"></a> </li>
        <li><a href="{% url 'stats:index' %}#stats"><img class="navbarstats" src="https://image.flaticon.com/icons/png/512/39/39915.png"></a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>