ntaps/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
import ntaps_profile.urls as ntaps_profile
import ntaps_add_friend.urls as ntaps_add_friend
import ntaps_update_status.urls as ntaps_update_status
import ntaps_stats.urls as ntaps_stats

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(ntaps_profile,namespace='profile')),
    url(r'^add_friend/', include(ntaps_add_friend,namespace='add_friend')),
    url(r'^update_status/', include(ntaps_update_status,namespace='update_status')),
    url(r'^stats/', include(ntaps_stats,namespace='stats')),
    url(r'^$', RedirectView.as_view(permanent=True, url='/update_status/'))
]

ntaps_add_friend/urls.py
from django.conf.urls import url
from .views import index, create
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'create/', create, name='create'),
]

ntaps_add_friend/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

ntaps_add_friend/forms.py
from django import forms

class Add_Friend_Form(forms.Form):
    name_error_messages = {
        'required': 'Nama teman kamu wajib diisi',
    }
    url_error_messages = {
        'required': 'Url teman kamu wajib diisi',
    }
    name_attrs = {
        'type': 'text',
        'class': 'input-text',
        'placeholder':'Masukan nama teman kamu...'
    }
    url_attrs = {
        'type': 'text',
        'class': 'input-text-inline-button',
        'placeholder':'Masukan url tugas teman kamu...'
    }

    name = forms.CharField(label='Name', required=True, widget=forms.TextInput(attrs=name_attrs), error_messages=name_error_messages)
    url = forms.CharField(label='URL', required=True, widget=forms.TextInput(attrs=url_attrs), error_messages=url_error_messages)

ntaps_add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import messages
from urllib import request
from .models import Friend
from .forms import Add_Friend_Form

# Create your views here.
response = {}
def index(request):
    html = 'add_friend/ntaps_add_friend.html'
    response['offset'] = int(request.GET.get('offset', '0'))
    response['next_offset'] = response['offset'] + 5;
    response['prev_offset'] = response['offset'] - 5;
    response['disable_next'] = True if response['next_offset'] > Friend.objects.all().count() else False;
    response['disable_prev'] = True if response['prev_offset'] < 0 else False;
    start = response['offset']
    finish = response['offset'] + 5;
    response['friends'] = Friend.objects.all().order_by('-created_at')[start:finish]
    response['add_friend_form'] = Add_Friend_Form

    return render(request, html, response)

def create(request):
    form = Add_Friend_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        if (check_url(append_http(request.POST['url']))):
            response['name'] = request.POST['name']
            response['url'] = append_http(request.POST['url'])
            friend = Friend(name=response['name'], url=response['url'])
            friend.save()
            return HttpResponseRedirect('/add_friend/')
        else:
            messages.error(request, 'Url temanmu tidak bisa diakses. Format URL: http://ntaps.herokuapp.com')
            return HttpResponseRedirect('/add_friend/')
    else:
        for error, error_messages in form.errors.items():
            for message in error_messages:
                messages.error(request, message)
        return HttpResponseRedirect('/add_friend/')

def append_http(url):
    if((url[:7] != "http://") and (url[:8] != "https://")):
        return "http://{}".format(url)
    else:
        return url
def check_url(url):
    try:
        code = request.urlopen(url).getcode()
        return True
    except:
        return False;

ntaps_add_friend/templates/add_friend/ntaps_add_friend.html
{% extends "add_friend/layout/base.html" %}
{% block content %}
<div class="wrapper-page">
  <div class="wrapper-kiri">
      <div class="wrapper-content">
        <h1 class="friend-title text-white">Add your friends!</h1>
        <form method="POST" action="{% url 'add_friend:create' %}" class="form-main">
          {% csrf_token %}
          <div>
            {{ add_friend_form.name }}
          </div>
          <div>
            {{ add_friend_form.url }}<button type="submit" class="inline-button">Submit</button>
          </div>
          {% for message in messages %}
          <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
          {% endfor %}
        </form>
      </div>
  </div>
  <div class="wrapper-kanan">
    <div class="wrapper-content">
      <h1 class="friend-title">My friends
        <span style="float: right">
        {% if disable_prev %}
        <a href="#" class="disabled">&#8249;</a>
        {% else %}
        <a href="{% url 'add_friend:index' %}?offset={{ prev_offset }}"">&#8249;</a>
        {% endif %}
        {% if disable_next %}
        <a href="#" class="disabled">&#8250;</a>
        {% else %}
        <a href="{% url 'add_friend:index' %}?offset={{ next_offset }}">&#8250;</a>
        {% endif %}
        </span>
      </h1>
      <hr class="divider">
      <div class="flex-list">
        {% for friend in friends %}
        <div class="flex-list-item friend-list-item">
          <h4 class="list-item-title">{{ friend.name }}</h4>
          <a href="{{ friend.url }}"><p class="list-item-content-text">{{ friend.url }}</p></a>
          <p class="list-item-content-text"><i>{{ friend.created_at }}</i></p>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}